### ISSUE TITLE
error in Box-Cox transformation

### ISSUE THREAD

**Issue by knutj** [trislett/TFCE_mediation#19]
When I use Box-Cox transformation I get this error.

Traceback (most recent call last):
  File "/home/knutjb/pymediator/bin/tm_tools", line 164, in <module>
    args.func(args)
  File "/home/knutjb/pymediator/lib64/python3.7/site-packages/tfce_mediation/tools/boxcox_transformation.py", line 65, in run
    affine_mask = img_surf.get_affine()
  File "/home/knutjb/pymediator/lib/python3.7/site-packages/nibabel/deprecator.py", line 181, in deprecated_func
    raise error_class(message)
nibabel.deprecator.ExpiredDeprecationError: get_affine method is deprecated.
Please use the ``img.affine`` property instead.

* deprecated from version: 2.1
After updating to img,affine 

There has been an update to Nibabel. I am using Python 3.7.

**Comment by knutj** [comment]
It caused by using a deprecated function in Nibabel.
