### ISSUE TITLE
Pip install yields TabError

### ISSUE THREAD

**Issue by Shotgunosine** [trislett/TFCE_mediation#3]
I tried to pip install your package as suggested in the wiki:
`pip install -U tfce-mediation`
 and I got a TabError:
```
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    configuration = configuration
  File "/Users/nielsond/miniconda3/envs/nhw_ipynb/lib/python3.6/site-packages/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 45, in configuration
    CONFIG.add_subpackage(PACKAGE_NAME)
  File "/Users/nielsond/miniconda3/envs/nhw_ipynb/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1029, in add_subpackage
    caller_level = 2)
  File "/Users/nielsond/miniconda3/envs/nhw_ipynb/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 998, in get_subpackage
    caller_level = caller_level + 1)
  File "/Users/nielsond/miniconda3/envs/nhw_ipynb/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 911, in _get_configuration_from_setup_py
    ('.py', 'U', 1))
  File "/Users/nielsond/miniconda3/envs/nhw_ipynb/lib/python3.6/site-packages/numpy/compat/py3k.py", line 122, in npy_load_module
    return importlib.machinery.SourceFileLoader(name, fn).load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "tfce_mediation/setup.py", line 19
    CONFIG.add_data_dir("adjacency_sets")
                                        ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by trislett** [comment]
Hi @Shotgunosine,
My apologies for replying late. It seems a couple of spaces found their way into my setup script. I've just uploaded a new version of TFCE_mediation (1.3.7) that should fix the issue.
